name: CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: [23.2]
        elixir: [1.11.3]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1.5
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
          experimental-otp: true

      - uses: actions/cache@v1
        id: deps-cache
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - uses: actions/cache@v1
        id: build-cache
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - run: mix deps.get
      - run: mix format --check-formatted
      - run: mix test

  deploy:
    needs: test # Will only run if the test job succeeds
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    env:
      SECRET_KEY_BASE: ${{ secrets.PHX_SECRET_KEY_BASE }}

    steps:
      - uses: actions/checkout@v2
        with:
          ref: main # Checkout out master instead of the latest commit
          fetch-depth: 0 # Checkout the whole branch
      - uses: actions/setup-elixir@v1.5
        with:
          otp-version: 23.2
          elixir-version: 1.11.3
          experimental-otp: true
      - run: mix deps.get --only prod
      - run: MIX_ENV=prod mix compile
      - run: npm install --prefix ./assets
      - run: npm run deploy --prefix ./assets
      - run: mix phx.digest
      - run: MIX_ENV=prod mix release

      - name: Copying release to prod server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          # rm: true
          source: "_build/prod/rel/qwixx/"
          target: "${{ secrets.DEPLOY_DIR }}"

      - name: Executing remote  command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          USERNAME: ${{ secrets.DEPLOY_USER }}
          KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            whoami
            ls -al
